name: Docker Hub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        id: vars
        shell: bash
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kippenhof/actual-server:latest, kippenhof/actual-server:${SHORT_SHA}
      -
        name: Build and push Alpine
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.alpine
          push: true
          tags: kippenhof/actual-server:latest-alpine,kippenhof/actual-server:${SHORT_SHA}-alpine
